name: Infrastructure Deployment Pipeline

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: cd Terraform && terraform init

      - name: Terraform apply
        run: cd Terraform && terraform apply -auto-approve

      - name: Save inventory
        run: cat Terraform/inventory.ini > inventory.ini

      - name: Upload inventory file
        uses: actions/upload-artifact@v4
        with:
          name: inventory
          path: inventory.ini

  ansible:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download inventory file
        uses: actions/download-artifact@v4
        with:
          name: inventory

      - name: Move inventory file
        run: mv inventory.ini Ansible/inventory.ini

      - name: Setup Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Run Ansible playbook
        run: cd Ansible && ansible-playbook -i inventory.ini playbook.yml
